[2023-08-16T11:57:52.720+0000] {processor.py:157} INFO - Started process (PID=155) to work on /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-08-16T11:57:52.752+0000] {processor.py:826} INFO - Processing file /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-08-16T11:57:52.781+0000] {logging_mixin.py:149} INFO - [2023-08-16T11:57:52.768+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-08-16T11:58:22.940+0000] {logging_mixin.py:149} INFO - [2023-08-16T11:58:22.931+0000] {timeout.py:68} ERROR - Process timed out, PID: 155
[2023-08-16T11:58:23.011+0000] {logging_mixin.py:149} INFO - [2023-08-16T11:58:22.974+0000] {dagbag.py:350} ERROR - Failed to import: /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 32, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 12, in <module>
    from pandas.core.arrays.interval import IntervalArray
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/arrays/interval.py", line 92, in <module>
    from pandas.core.indexes.base import ensure_index
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.2/best-practices.html#reducing-dag-complexity, PID: 155
[2023-08-16T11:58:23.024+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-08-16T11:58:23.194+0000] {processor.py:179} INFO - Processing /home/airflow/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 30.542 seconds
